/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

/**
 *
 * @author LENOVO
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUbahPin = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnTransfer1 = new javax.swing.JButton();
        btnPenarikan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSetorTunai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        btnUbahPin.setBackground(new java.awt.Color(255, 255, 255));
        btnUbahPin.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnUbahPin.setText("UBAH PIN");
        btnUbahPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPinActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbahPin);
        btnUbahPin.setBounds(770, 290, 220, 80);

        btnSaldo.setBackground(new java.awt.Color(255, 255, 255));
        btnSaldo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSaldo.setText("INFORMASI SALDO ");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaldo);
        btnSaldo.setBounds(40, 110, 220, 80);

        btnTransfer1.setBackground(new java.awt.Color(255, 255, 255));
        btnTransfer1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnTransfer1.setText("TRANSFER");
        btnTransfer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransfer1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransfer1);
        btnTransfer1.setBounds(40, 230, 220, 80);

        btnPenarikan.setBackground(new java.awt.Color(255, 255, 255));
        btnPenarikan.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnPenarikan.setText("PENARIKAN");
        btnPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenarikanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPenarikan);
        btnPenarikan.setBounds(40, 350, 220, 80);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(410, 460, 220, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HALAMAN UTAMA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 0, 360, 110);

        btnSetorTunai.setBackground(new java.awt.Color(255, 255, 255));
        btnSetorTunai.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSetorTunai.setText("SETOR TUNAI");
        btnSetorTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorTunaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnSetorTunai);
        btnSetorTunai.setBounds(770, 150, 220, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
        new InformasiSaldo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnUbahPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPinActionPerformed
        // TODO add your handling code here:
        new UbahPIN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUbahPinActionPerformed

    private void btnTransfer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransfer1ActionPerformed
        // TODO add your handling code here:
        new Transfer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransfer1ActionPerformed

    private void btnPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenarikanActionPerformed
        // TODO add your handling code here:
        new TarikTunai().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPenarikanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new PIN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSetorTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorTunaiActionPerformed
        // TODO add your handling code here:
        new SetorTunai().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSetorTunaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPenarikan;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSetorTunai;
    private javax.swing.JButton btnTransfer1;
    private javax.swing.JButton btnUbahPin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
