/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

/**
 *
 * @author LENOVO
 */
public class JumlahTransfer extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public JumlahTransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKembaliTransfer = new javax.swing.JButton();
        btnNominal = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn501 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jumlah Transfer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 10, 370, 100);

        btnKembaliTransfer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKembaliTransfer.setText("Kembali");
        btnKembaliTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliTransferActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembaliTransfer);
        btnKembaliTransfer.setBounds(230, 440, 250, 100);

        btnNominal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnNominal.setText("Masukkan Nominal");
        btnNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominalActionPerformed(evt);
            }
        });
        jPanel1.add(btnNominal);
        btnNominal.setBounds(630, 440, 230, 100);

        btn50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn50.setText("Rp 50.000");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });
        jPanel1.add(btn50);
        btn50.setBounds(30, 120, 190, 110);

        btn100.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn100.setText("Rp 100.000");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100);
        btn100.setBounds(30, 260, 190, 100);

        btn200.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn200.setText("Rp 200.000");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });
        jPanel1.add(btn200);
        btn200.setBounds(780, 110, 210, 100);

        btn501.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn501.setText("Rp 500.000");
        btn501.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn501ActionPerformed(evt);
            }
        });
        jPanel1.add(btn501);
        btn501.setBounds(780, 250, 210, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliTransferActionPerformed
        // TODO add your handling code here:
        new Transfer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliTransferActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        // TODO add your handling code here:
        new TransferBerhasil50().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn50ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
        new TransferBerhasil100().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        // TODO add your handling code here:
        new TransferBerhasil200().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn200ActionPerformed

    private void btnNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominalActionPerformed
        // TODO add your handling code here:
        new TransferNominal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNominalActionPerformed

    private void btn501ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn501ActionPerformed
        // TODO add your handling code here:
        new TransferBerhasil500().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn501ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JumlahTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JumlahTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JumlahTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JumlahTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JumlahTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn501;
    private javax.swing.JButton btnKembaliTransfer;
    private javax.swing.JButton btnNominal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
