/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class SetorTunai extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    InformasiSaldoModel saldo;
    
    public SetorTunai() {
        initComponents();
        txtBerhasil.setVisible(false);
        txtGagal.setVisible(false);
    }

    public JTextField getTxtNominal() {
        return txtNominal;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtGagal = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        btnLanjutkanTransfer = new javax.swing.JButton();
        btnHalaman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSetoran = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBerhasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        txtGagal.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        txtGagal.setForeground(new java.awt.Color(255, 51, 51));
        txtGagal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGagal.setText("Setoran Gagal");
        jPanel1.add(txtGagal);
        txtGagal.setBounds(370, 370, 310, 50);

        txtNominal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(txtNominal);
        txtNominal.setBounds(290, 180, 480, 50);

        btnLanjutkanTransfer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLanjutkanTransfer.setText("Lanjutkan");
        btnLanjutkanTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutkanTransferActionPerformed(evt);
            }
        });
        jPanel1.add(btnLanjutkanTransfer);
        btnLanjutkanTransfer.setBounds(740, 420, 220, 80);

        btnHalaman.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnHalaman.setText("Halaman Utama");
        btnHalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnHalaman);
        btnHalaman.setBounds(140, 430, 220, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masukkan Uang Setoran");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 60, 580, 130);

        txtSaldo.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaldo.setText("Rp. ");
        jPanel1.add(txtSaldo);
        txtSaldo.setBounds(450, 290, 280, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah Setoran :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 240, 220, 50);

        txtSetoran.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtSetoran.setForeground(new java.awt.Color(255, 255, 255));
        txtSetoran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSetoran.setText("Rp. ");
        jPanel1.add(txtSetoran);
        txtSetoran.setBounds(520, 240, 280, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sisa Saldo :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 290, 220, 50);

        txtBerhasil.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        txtBerhasil.setForeground(new java.awt.Color(0, 255, 51));
        txtBerhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBerhasil.setText("Setoran Berhasil");
        jPanel1.add(txtBerhasil);
        txtBerhasil.setBounds(370, 350, 310, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalamanActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHalamanActionPerformed

    private void btnLanjutkanTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutkanTransferActionPerformed
        // TODO add your handling code here:
        saldo=new InformasiSaldoModel();
        saldo.setSetoran(this.getTxtNominal().getText());
        if(saldo.getSaldo()>0){
            saldo.prosesSetoran();
            txtSaldo.setVisible(true);
            txtSaldo.setText("Rp. "+saldo.getSaldo());
            txtSetoran.setVisible(true);
            txtSetoran.setText("Rp. "+this.getTxtNominal().getText());
            txtBerhasil.setVisible(true);
            txtNominal.setText("");
        }else{
            txtBerhasil.setVisible(false);
            txtGagal.setVisible(true);
        }
    }//GEN-LAST:event_btnLanjutkanTransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetorTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetorTunai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHalaman;
    private javax.swing.JButton btnLanjutkanTransfer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBerhasil;
    private javax.swing.JLabel txtGagal;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtSetoran;
    // End of variables declaration//GEN-END:variables
}
