/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

/**
 *
 * @author LENOVO
 */
public class TransferBerhasil100 extends javax.swing.JFrame {

    /**
     * Creates new form InformasiSaldo
     */
    public TransferBerhasil100() {
        initComponents();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        InformasiSaldoModel transfer1 = new InformasiSaldoModel();
        labelTransfer.setText("Rp "+transfer1.getTransfer2());
        labelSaldo.setText("Rp "+saldo.getSaldo2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTransfer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        labelTransfer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTransfer.setForeground(new java.awt.Color(255, 0, 51));
        labelTransfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTransfer.setText("Rp. ");
        jPanel1.add(labelTransfer);
        labelTransfer.setBounds(470, 200, 430, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Transfer Berhasil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 30, 450, 100);

        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(340, 480, 390, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Saldo anda saat ini");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 300, 430, 80);

        labelSaldo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(255, 0, 51));
        labelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSaldo.setText("Rp. ");
        jPanel1.add(labelSaldo);
        labelSaldo.setBounds(470, 300, 430, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah Transfer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 200, 430, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferBerhasil100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferBerhasil100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferBerhasil100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferBerhasil100.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferBerhasil100().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTransfer;
    // End of variables declaration//GEN-END:variables
}
