/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

/**
 *
 * @author LENOVO
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoRekening = new javax.swing.JTextField();
        btnLanjutkanTransfer = new javax.swing.JButton();
        btnKembaliTransfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Masukkan No Rekening Tujuan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 60, 580, 130);
        jPanel1.add(txtNoRekening);
        txtNoRekening.setBounds(290, 180, 480, 40);

        btnLanjutkanTransfer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLanjutkanTransfer.setText("Lanjutkan");
        btnLanjutkanTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutkanTransferActionPerformed(evt);
            }
        });
        jPanel1.add(btnLanjutkanTransfer);
        btnLanjutkanTransfer.setBounds(730, 370, 220, 80);

        btnKembaliTransfer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKembaliTransfer.setText("Kembali");
        btnKembaliTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliTransferActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembaliTransfer);
        btnKembaliTransfer.setBounds(90, 380, 220, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliTransferActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliTransferActionPerformed

    private void btnLanjutkanTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutkanTransferActionPerformed
        // TODO add your handling code here:
        new JumlahTransfer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLanjutkanTransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembaliTransfer;
    private javax.swing.JButton btnLanjutkanTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNoRekening;
    // End of variables declaration//GEN-END:variables
}
