/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_AhmadFarisAlmuzakki_2101092028;

/**
 *
 * @author LENOVO
 */
public class UbahPIN extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public UbahPIN() {
        initComponents();
        txtBerhasil.setVisible(false);
        txtGagal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        passwordTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtGagal = new javax.swing.JLabel();
        txtBerhasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(null);

        Header.setBackground(new java.awt.Color(102, 102, 255));
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setLayout(null);

        passwordTXT.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        passwordTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Header.add(passwordTXT);
        passwordTXT.setBounds(330, 220, 350, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Masukkan PIN Baru Anda");
        Header.add(jLabel4);
        jLabel4.setBounds(260, 140, 490, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText("LANJUTKAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Header.add(jButton1);
        jButton1.setBounds(760, 450, 220, 120);

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnKembali.setText("BATAL");
        Header.add(btnKembali);
        btnKembali.setBounds(20, 440, 220, 120);

        txtGagal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtGagal.setForeground(new java.awt.Color(255, 51, 51));
        txtGagal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGagal.setText("Ubah PIN Gagal !");
        Header.add(txtGagal);
        txtGagal.setBounds(330, 340, 330, 50);

        txtBerhasil.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtBerhasil.setForeground(new java.awt.Color(0, 255, 51));
        txtBerhasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBerhasil.setText("Ubah PIN Berhasil !");
        Header.add(txtBerhasil);
        txtBerhasil.setBounds(330, 300, 330, 50);

        getContentPane().add(Header);
        Header.setBounds(0, 0, 1020, 600);

        setSize(new java.awt.Dimension(1046, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PinModel pin = new PinModel();
        if(passwordTXT.getText().equals(pin.getPin())){
            txtGagal.setVisible(true);
            txtBerhasil.setVisible(false);
        } else{
            txtGagal.setVisible(false);
            txtBerhasil.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbahPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbahPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbahPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbahPIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahPIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField passwordTXT;
    private javax.swing.JLabel txtBerhasil;
    private javax.swing.JLabel txtGagal;
    // End of variables declaration//GEN-END:variables
}
